# Generated by Django 3.2 on 2022-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
